/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ewb.qa.tdd.GUI;

import ewb.qa.tdd.SQLObj;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JTable;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.table.TableModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import org.apache.poi.ss.util.NumberToTextConverter;

/**
 *
 * @author JPE61800
 */
public class AdmnistratorGUI extends javax.swing.JFrame {

    private int flagmode = 0;
    //private static Connection conn = ewb.qa.tdd.SQLObj.ConnToDB();
    /**
     * Creates new form AdmnistratorGUI
     */
    public AdmnistratorGUI() {
        initComponents();
        
        loadUserTypeLst();
        loadUserProfileTbl();
        defaultsetttings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UserIdTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        UserTypeDescCmb = new javax.swing.JComboBox<>();
        UserTypeIdTxt = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();
        ChangeBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        NewBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserProfileTbl = new javax.swing.JTable();
        IdTxt = new javax.swing.JTextField();
        CreateTestCaseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Profiles");

        jLabel1.setText("User ID :");

        UserIdTxt.setText("jTextField1");
        UserIdTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UserIdTxtKeyPressed(evt);
            }
        });

        jLabel2.setText("User Type :");

        UserTypeDescCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        UserTypeDescCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTypeDescCmbActionPerformed(evt);
            }
        });

        UserTypeIdTxt.setText("jTextField2");

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        ChangeBtn.setText("Change");
        ChangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeBtnActionPerformed(evt);
            }
        });

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        NewBtn.setText("New");
        NewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBtnActionPerformed(evt);
            }
        });

        UserProfileTbl = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        UserProfileTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        UserProfileTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserProfileTblMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(UserProfileTbl);

        IdTxt.setText("jTextField3");

        CreateTestCaseBtn.setText("Create Test Cases");
        CreateTestCaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateTestCaseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreateTestCaseBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChangeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelBtn))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UserTypeDescCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UserTypeIdTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UserIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(UserTypeDescCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserTypeIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn)
                    .addComponent(CancelBtn)
                    .addComponent(SaveBtn)
                    .addComponent(ChangeBtn)
                    .addComponent(NewBtn)
                    .addComponent(CreateTestCaseBtn))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBtnActionPerformed
        // TODO add your handling code here:
        flagmode = 1;
        newrecord();
    }//GEN-LAST:event_NewBtnActionPerformed

    private void ChangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeBtnActionPerformed
        // TODO add your handling code here:
        flagmode = 2;
        changerecord();
    }//GEN-LAST:event_ChangeBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        
        int Id = 0;
        String UserId = UserIdTxt.getText();
        int UserTypeId = Integer.parseInt(UserTypeIdTxt.getText());
        if(flagmode == 1){
            InsertNewRecord(UserId, UserTypeId);
            flagmode = 0;
            loadUserProfileTbl();
        }
        else if(flagmode == 2){
            Id = Integer.parseInt(IdTxt.getText());
            UpdateExistingRecord(Id, UserId, UserTypeId);
            flagmode = 0;
            loadUserProfileTbl();
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void UserTypeDescCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTypeDescCmbActionPerformed
        // TODO add your handling code here:
        JFrame jFrame = new JFrame();
        try{
            Connection conn = ewb.qa.tdd.SQLObj.ConnToDB();
            CallableStatement cs = conn.prepareCall("{call Search_UserTypeId_ByUserTypeDesc(?)}");
            String UserTypeDesc = UserTypeDescCmb.getSelectedItem().toString();
            
            cs.setNString(1, UserTypeDesc);
            ResultSet rs = cs.executeQuery();
            if(rs.next()){
                /*
                1-UT.ID,
                2-UT.USERTYPE_ID,
                3-UT.USERTYPE_DESC                
                */
                
                UserTypeIdTxt.setText(NumberToTextConverter.toText(rs.getInt(2)));
            }
            rs.close();
            cs.close();
            conn.close();
                    
        }
        catch(Exception ex){
                String errMessage = null;

                errMessage = "Error Message: " + ex.getMessage() + 
                   "\n" + "Error Localize Message: " + ex.getLocalizedMessage() + 
                   "\n" + "Stack Trace: " + ex.getStackTrace() + 
                   "\n" + "Cause: " + ex.getCause();

                System.out.println(errMessage);

                //if(execFlag <= 0 ){
                JOptionPane.showMessageDialog(jFrame,  "Populate User Type ID Failed " + 
                               "\n" + errMessage, "Administrator GUI", JOptionPane.ERROR_MESSAGE);              
        }
    }//GEN-LAST:event_UserTypeDescCmbActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainGUI execPage = new MainGUI();
        execPage.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void UserIdTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserIdTxtKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if(key == KeyEvent.VK_ENTER){
            String UserId = UserIdTxt.getText();
            UserIdTxt.setText(UserId.toUpperCase());
        }
    }//GEN-LAST:event_UserIdTxtKeyPressed

    private void UserProfileTblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserProfileTblMousePressed
        // TODO add your handling code here:
        int indexRow = UserProfileTbl.getSelectedRow();
        TableModel model = UserProfileTbl.getModel();
        
        IdTxt.setText(model.getValueAt(indexRow, 0).toString());
        UserIdTxt.setText(model.getValueAt(indexRow, 1).toString());
        UserTypeDescCmb.setSelectedItem(model.getValueAt(indexRow, 3).toString());
        
    }//GEN-LAST:event_UserProfileTblMousePressed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        // TODO add your handling code here:
        defaultsetttings();
        flagmode = 0;
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void CreateTestCaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateTestCaseBtnActionPerformed
        // TODO add your handling code here:
        JFrame jFrame = new JFrame();
        try{
            Connection conn = ewb.qa.tdd.SQLObj.ConnToDB();
            CallableStatement cs = conn.prepareCall("{call Search_AllTestCases_ByProjCodeUserID(?,?)}");
        }
        catch(Exception ex){
            
        }
    }//GEN-LAST:event_CreateTestCaseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmnistratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmnistratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmnistratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmnistratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmnistratorGUI().setVisible(true);
            }
        });
    }

    private void loadUserTypeLst(){
        JFrame jFrame = new JFrame();
        try{
            Connection conn = ewb.qa.tdd.SQLObj.ConnToDB();
            CallableStatement cs = conn.prepareCall("{call Search_AllUserType()}");
            
            ResultSet rs = cs.executeQuery();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            UserTypeDescCmb.setModel(model);

            while(rs.next()){
                /*
                1-UT.ID,
                2-UT.USERTYPE_ID,
                3-UT.USERTYPE_DESC
                */
                UserTypeDescCmb.addItem(rs.getNString(3));
            }
            rs.close();
            cs.close();
            conn.close();
        }
        catch(Exception ex){
                String errMessage = null;

                errMessage = "Error Message: " + ex.getMessage() + 
                   "\n" + "Error Localize Message: " + ex.getLocalizedMessage() + 
                   "\n" + "Stack Trace: " + ex.getStackTrace() + 
                   "\n" + "Cause: " + ex.getCause();

                System.out.println(errMessage);

                //if(execFlag <= 0 ){
                JOptionPane.showMessageDialog(jFrame,  "User Type listing Failed " + 
                               "\n" + errMessage, "Administrator GUI", JOptionPane.ERROR_MESSAGE);               
        }
    }
    
    private void loadUserProfileTbl(){
        JFrame jFrame = new JFrame();
        try{
            Connection conn = ewb.qa.tdd.SQLObj.ConnToDB();
            CallableStatement cs = conn.prepareCall("{call Search_AllUserProfile()}");
            ResultSet rs = cs.executeQuery();
            
            String Id = "";
            String UserId = "";
            String UserTypeId = "";
            String UserTypeDesc = "";
            UserProfileTbl.setModel(new DefaultTableModel(null, new String[] {"ID", "User ID", "Type ID", "Type Desc"}));
            while(rs.next()){
                Id = NumberToTextConverter.toText(rs.getInt(1));
                UserId = rs.getNString(2);
                UserTypeId = NumberToTextConverter.toText(rs.getInt(3));
                UserTypeDesc = rs.getNString(4);
                
                String[] arrTbl = {Id, UserId, UserTypeId, UserTypeDesc};
                DefaultTableModel model = (DefaultTableModel)UserProfileTbl.getModel();
                model.addRow(arrTbl);
                
            }
            rs.close();
            cs.close();
            conn.close();
        }
        catch(Exception ex){
                String errMessage = null;

                errMessage = "Error Message: " + ex.getMessage() + 
                   "\n" + "Error Localize Message: " + ex.getLocalizedMessage() + 
                   "\n" + "Stack Trace: " + ex.getStackTrace() + 
                   "\n" + "Cause: " + ex.getCause();

                System.out.println(errMessage);

                //if(execFlag <= 0 ){
                JOptionPane.showMessageDialog(jFrame,  "Populate User Profile listing Failed " + 
                               "\n" + errMessage, "Administrator GUI", JOptionPane.ERROR_MESSAGE);                
        }
    }
    
    private void InsertNewRecord(String givenUserId, int givenUserTypeId){
        JFrame jFrame = new JFrame();
        try{
            Connection conn = ewb.qa.tdd.SQLObj.ConnToDB();
            CallableStatement cs = conn.prepareCall("{call Insert_UserProfile(?,?)}");
            cs.setNString(1, givenUserId);
            cs.setInt(2, givenUserTypeId);
            
            int response = JOptionPane.showConfirmDialog(jFrame, "Are you sure you want to Insert the Created new User Profile?", "Adminstrator GUI", JOptionPane.YES_NO_OPTION);
            if(response == 0){
                int saveflag = cs.executeUpdate();
                if(saveflag < 0){
                    JOptionPane.showMessageDialog(jFrame, "New created User Profile has been successfully saved", "Administrator GUI", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            cs.close();
            conn.close();
        }
        catch(Exception ex){
                String errMessage = null;

                errMessage = "Error Message: " + ex.getMessage() + 
                   "\n" + "Error Localize Message: " + ex.getLocalizedMessage() + 
                   "\n" + "Stack Trace: " + ex.getStackTrace() + 
                   "\n" + "Cause: " + ex.getCause();

                System.out.println(errMessage);

                //if(execFlag <= 0 ){
                JOptionPane.showMessageDialog(jFrame,  "Insert New User Profiel failed" + 
                               "\n" + errMessage, "Administrator GUI", JOptionPane.ERROR_MESSAGE);              
        }
    }
    
    private void UpdateExistingRecord(int givenId, String givenUserId, int givenUserTypeId){
        JFrame jFrame = new JFrame();
        try{
            Connection conn = ewb.qa.tdd.SQLObj.ConnToDB();
            CallableStatement cs = conn.prepareCall("{call Update_UserProfile(?,?,?)}");
            cs.setInt(1, givenId);
            cs.setNString(2, givenUserId);
            cs.setInt(3, givenUserTypeId);
            
            int response = JOptionPane.showConfirmDialog(jFrame, "Are you sure you want to change the following record?", "Administrator GUI", JOptionPane.YES_NO_OPTION);
            if(response == 0){
                int saveflag = cs.executeUpdate();
                if(saveflag < 0){
                    JOptionPane.showMessageDialog(jFrame, "Record has been successfully updated", "Administrator", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
        catch(Exception ex){
                String errMessage = null;

                errMessage = "Error Message: " + ex.getMessage() + 
                   "\n" + "Error Localize Message: " + ex.getLocalizedMessage() + 
                   "\n" + "Stack Trace: " + ex.getStackTrace() + 
                   "\n" + "Cause: " + ex.getCause();

                System.out.println(errMessage);

                //if(execFlag <= 0 ){
                JOptionPane.showMessageDialog(jFrame,  "Update User Profiel failed" + 
                               "\n" + errMessage, "Administrator GUI", JOptionPane.ERROR_MESSAGE);                 
        }
    }
    
    private void defaultsetttings(){
        IdTxt.setEnabled(false);
        UserTypeIdTxt.setEnabled(false);
        
        IdTxt.setText("");
        UserTypeIdTxt.setText("");
        UserIdTxt.setText("");
        
        NewBtn.setEnabled(true);
        ChangeBtn.setEnabled(false);
        SaveBtn.setEnabled(false);
        CancelBtn.setEnabled(false);
    }
    
    private void newrecord(){
        IdTxt.setText("");
        UserIdTxt.setText("");
        
        NewBtn.setEnabled(false);
        ChangeBtn.setEnabled(false);
        SaveBtn.setEnabled(true);
        CancelBtn.setEnabled(true);
    }
    
    private void changerecord(){
        NewBtn.setEnabled(false);
        ChangeBtn.setEnabled(false);
        SaveBtn.setEnabled(true);
        CancelBtn.setEnabled(true);
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton ChangeBtn;
    private javax.swing.JButton CreateTestCaseBtn;
    private javax.swing.JTextField IdTxt;
    private javax.swing.JButton NewBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField UserIdTxt;
    private javax.swing.JTable UserProfileTbl;
    private javax.swing.JComboBox<String> UserTypeDescCmb;
    private javax.swing.JTextField UserTypeIdTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
