/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ewb.qa.tdd.GUI;

import ewb.qa.tdd.SQLObj;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JTable;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.table.TableModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import org.apache.poi.ss.util.NumberToTextConverter;

/**
 *
 * @author JPE61800
 */
public class LoginGUI extends javax.swing.JFrame {
    
    /**
     * Creates new form LoginGUI
     */
    private static String globalLoginId;
    
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LoginIdTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LoginBtn.setText("Enter");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        CancelBtn.setText("Exit");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to QA Test Data Driven App");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel2.setText("Login ID :");

        LoginIdTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginIdTxtKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LoginIdTxt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LoginBtn)
                                .addGap(70, 70, 70)
                                .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LoginIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginBtn)
                    .addComponent(CancelBtn))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        String loginid = LoginIdTxt.getText().toUpperCase();
        userLogin(loginid);
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void userLogin(String givenLoginId){
        JFrame jFrame = new JFrame();
        
        if(givenLoginId.equals("")){
            JOptionPane.showMessageDialog(jFrame, "Login ID has invalid value or empty", "Login Page", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try{
                Connection conn = ewb.qa.tdd.SQLObj.ConnToDB();
                CallableStatement cs = conn.prepareCall("{call Search_UserProfile_ByUserId(?)}");
                cs.setNString(1, givenLoginId);
                
                ResultSet rs = cs.executeQuery();
                if(rs.next()){
                    /*		
                    UP.ID,
                    UP.USERID,
                    UP.USERTYPE
                    */
                    int UPId = rs.getInt(1);
                    String UPUserId = rs.getNString(2);
                    int UPUserType = rs.getInt(3);

                    setLoginId(UPUserId.toUpperCase());                                    
                    setUserType(UPUserType);
                    
                    setVisible(false);
                    MainGUI form = new MainGUI();
                    form.setVisible(true);            
                }
                else{
                    JOptionPane.showMessageDialog(jFrame, "User Login ID is not yet registered", "TDD Login Page", JOptionPane.INFORMATION_MESSAGE);
                }
                conn.close();

            }
            catch(Exception ex){
                    String errMessage = null;

                    errMessage = "Error Message: " + ex.getMessage() + 
                       "\n" + "Error Localize Message: " + ex.getLocalizedMessage() + 
                       "\n" + "Stack Trace: " + ex.getStackTrace() + 
                       "\n" + "Cause: " + ex.getCause();
                    
                JOptionPane.showMessageDialog(jFrame, "Database connection failed, contact your Administator for assistance." + "\n" + errMessage
                        , "Login Page", JOptionPane.ERROR_MESSAGE);
            }
        }        
    }
            
    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        this.setVisible(false);
        System.exit(0);
        
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //ewb.qa.tdd.main();
        
    }//GEN-LAST:event_formWindowOpened

    private void LoginIdTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginIdTxtKeyPressed
        // TODO add your handling code here:
        JFrame jFrame = new JFrame();
        int key = evt.getKeyCode();
        if(key == KeyEvent.VK_ENTER){
            String loginid = LoginIdTxt.getText().toUpperCase();
            if(validate_userprofile(loginid) == true){
                userLogin(loginid.toUpperCase());                
            }
            else{
                JOptionPane.showMessageDialog(jFrame, "User Profile doesn't exist, kindly contact your admistrator for access", "QA TDD - Test Automation App", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_LoginIdTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }
    
    public static void setLoginId(String givenValue){
        globalLoginId = givenValue.toUpperCase();
    }

    public static String getLoginId(){
        return globalLoginId;
    }
    
    private boolean validate_userprofile(String givenUserId){
        JFrame jFrame = new JFrame();
        boolean result = false;
        
        try{
            Connection conn = ewb.qa.tdd.SQLObj.ConnToDB();
            CallableStatement cs = conn.prepareCall("{call Search_UserProfile_ByUserId(?)}");
            cs.setNString(1, givenUserId);
            
            ResultSet rs = cs.executeQuery();
            if(rs.next()){
                /*
                1-UP.ID,
                2-UP.USERID,
                3-UP.USERTYPE                
                */
                
                setUserType(rs.getInt(3));
                result = true;
            }
            else{
                result = false;
            }
            
            rs.close();
            cs.close();
            conn.close();
            
            return result;
        }
        catch(Exception ex){
                    String errMessage = null;

                    errMessage = "Error Message: " + ex.getMessage() + 
                       "\n" + "Error Localize Message: " + ex.getLocalizedMessage() + 
                       "\n" + "Stack Trace: " + ex.getStackTrace() + 
                       "\n" + "Cause: " + ex.getCause();
                    
                JOptionPane.showMessageDialog(jFrame, "User validation failed." + "\n" + errMessage
                        , "Login Page", JOptionPane.ERROR_MESSAGE);            
            return result;
        }
    }
    
    private static int globalUserType;
    
    public static void setUserType(int givenUserType){
        globalUserType = givenUserType;
    }
    
    public static int getUserType(){
        return globalUserType;
    }
    
    private void create_userprofile(String givenUserId){
        
    }
    
    private void create_userprofile_testcaselist(){
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JTextField LoginIdTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
